### ISSUE TITLE
exclude sub taxa columns from taxon

### ISSUE THREAD

**Issue by mdoering** [Sp2000/coldp#1]
Consider removing all extended higher sub-ranks from the taxon table so we end up with just the classic Linnean ranks (KPCOFG) plus subgenus and superfamily.

Other higher ranks can and should still be given, but through the preferred parent-child model via parentID

**Comment by gdower** [comment]
Are you planning on dropping subgenus? Currently, we do include subgenus in CoL and dropping subgenus  could result in duplicate records. Would it make sense to include subgenus in the name table for zoological data?

**Comment by mdoering** [comment]
No, I am not planning to drop subgenus in this issue. I have updated the description so its hopefully understandable now

**Comment by mdoering** [comment]
Btw there is an infragenericEpithet field in Name which is used for the subgenus part of a name. On the Taxon side subgenus is purely the classification and will not show as part of the name

**Comment by mdoering** [comment]
Its useful to have a rich, flat classification so we are going to keep it. See also #3
