### ISSUE TITLE
Replace Taxon.provisional with status

### ISSUE THREAD

**Issue by mdoering** [Sp2000/coldp#13]

**Comment by gdower** [comment]
@mdoering Should I use these [enums](http://api.col.plus/vocab/taxonomicstatus) in the taxonomic status column? The [CoLDP readme](https://github.com/Sp2000/coldp#Synonym) uses those same [taxonomic status enums](http://api.col.plus/vocab/taxonomicstatus) in status for the Synonyms table, which might be a mistake.

**Comment by mdoering** [comment]
yes, its the same enum for status in syn n acc. But only the accepted/synonym subset should be used on taxon/synonym tables respectively

**Comment by mdoering** [comment]
@gdower sorry for the confusion, but I don't think we should change the format and replace provisional. The idea was very premature and related to the merger issue here:
https://github.com/Sp2000/colplus-backend/issues/332

Please ignore!
