### ISSUE TITLE
Rename Synonym?

### ISSUE THREAD

**Issue by mdoering** [Sp2000/coldp#8]
The term synonym is overloaded and understood differently between the botanical and zoological world. Should we better use a different terminology?

Suggestions from Global Team so far:
 - historical names
 - unaccepted names
 - previous names

**Comment by mjy** [comment]
We actually have a method "historical_names" for this context.  Unaccepted leans to heavily to an ICZN concept.  "Previous" perhaps fails because a name for a biological entity can be previous, then current, then previous, then current.

**Comment by yroskov** [comment]
The most accurate term is "**semantic synonyms**".

All suggested alternatives above have their weaknesses. 
- historical names - synonyms & combinations might be actual in modern alternative classifications
- unaccepted names - will be confused with unavailable names
- previous names - see my comments to historical names

**Comment by mjy** [comment]
This triggers memory of yesterday's conversations. In talking with @gdower I feel there is a bigger problem that I, at least, need to understand.

Is the Synonym table recording a relationship between a name and biological entity?  Yes or no answers only ;).

**Comment by yroskov** [comment]
My answer is Yes.
"Synonym" in zoology = "Subjective synonym" in botany, i.e. name based on different type specimen. Decision on relationship between two previously independent species is made by the expert after analysis of biological entities of those species.

**Comment by mdoering** [comment]
I like your label `synonyms & combinations`, @yroskov. Thats exactly what it is.
I personally do understand `synonym` sensu latu as exactly this. 
The term `synonym` is also widely used in data standards for this, e.g. in the former CoL Submission Format (ACEF), the [TDWG ontology hasSynonym relation](https://github.com/tdwg/ontology/blob/master/ontology/voc/TaxonConcept.rdf#L419), [TCS has synonym relation](https://github.com/tdwg/tcs/blob/master/TCS101/example_v101.xml#L354), the [EDIT Common Data Model](https://cybertaxonomy.eu/cdmlib/apidocs/eu/etaxonomy/cdm/model/taxon/Synonym.html) and many more information model handling names and taxa.

**Comment by mjy** [comment]
Once I understand the concept I don't care what the label is.  I do worry that the broader understanding will be hampered by "Synonym" as their introduction to the concept.  

"NamesForThisTaxon" ;)

**Comment by mdoering** [comment]
I am closing this as it is hard to find a satisfactoring terminology for everyone. 
And I think "synonym" is a widely used one at least, see above
